name: build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.5, 3.6, 3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Start MongoDB As Docker
      run: |
        apt-get update && \
        apt-get install --no-install-recommends -y \
            mongodb \
            libgtk2.0-0 \
            libnotify-dev \
            libgconf-2-4 \
            libnss3 \
            libxss1 \
            libasound2 \
            libxtst6 \
            xvfb && \
            rm -rf /var/lib/apt/lists/*
        mongod --quiet --smallfiles --fork --logpath /var/log/mongodb.log >/dev/null
        
    - name: Install Dependences for Python ${{matrix.python-version}}
      run: |
        conda env create -n label-coach -q python=${PYVER} -f environment.yml
      env:
        PYVER: ${{ matrix.python-version }}
    - name: Install package 
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate label-coach
    - name: Install node
      uses: dcodeIO/setup-node-nvm@master
      with:
        node-version: node
        node-mirror: https://nodejs.org/download/v8-canary/
    - name: npm install
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate label-coach
        npm config set python `which python`
        cd ./label_coach/
        npm install -g npm
        npm install
    - name: Install girder plugin
      run: |
        export PATH="/usr/share/miniconda/bin:$PATH"
        source activate label-coach
        pwd
        girder-install plugin -s $HOME/work/label-coach/label-coach/label_coach
        girder-install web
